build:
  tags:
    - sw/web200
  script: 
    - rsync -avz $PWD/ /localsrc/php72/akita-erp --exclude ".git" --exclude "storage" --exclude "public/phpMyAdmin" --exclude "README.md" --exclude ".env"
  only:
    - develop